In [1]:
#Pytorch Basics

In [2]:
import torch

In [6]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [9]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype = torch.float32,device = device, requires_grad = True)

In [10]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [11]:
print(my_tensor.device)

cpu


In [15]:
x = torch.empty(size = (3,3))

In [16]:
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [13]:
x = torch.zeros((3,3))

In [14]:
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [17]:
x = torch.eye(5,5)

In [18]:
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [20]:
x =torch.linspace(start = 0.2, end = 2, steps = 10)

In [21]:
print(x)

tensor([0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000, 1.8000,
        2.0000])


In [22]:
x = torch.rand((3,3))
print(x)

tensor([[0.0872, 0.5704, 0.5322],
        [0.6807, 0.1709, 0.8543],
        [0.8629, 0.4525, 0.8560]])


In [24]:
x = torch.arange(start=5, end =10, step=1)
print(x)

tensor([5, 6, 7, 8, 9])


In [25]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [26]:
## Converting the tensors to other types

In [27]:
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [28]:
##Maths Operations

In [29]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [30]:
#Addition 
z = torch.empty(3)
torch.add(x,y,out=z)
print(z)

tensor([10., 10., 10.])


In [31]:
z=x+y

In [32]:
print(z)

tensor([10, 10, 10])


In [33]:
#Subtraction
z= x-y
print(z)

tensor([-8, -6, -4])


In [35]:
#Division
z = torch.true_divide(x,y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [37]:
#Inplace operations
t = torch.zeros(3)
t.add_(x)
t += x
print(t)

tensor([2., 4., 6.])


In [39]:
#Exponentiation
Z = x.pow(2)
z = x**2
print(z)

tensor([1, 4, 9])


In [40]:
#Simple comparison
z = x > 0
z = x < 0


In [46]:
#Matrix Multiplication
x1 = torch.rand(2,5)
x2 = torch.rand(5,3)
x3 = torch.mm(x1,x2)
x4 = x1.mm(x2)
print(x3,x4)

tensor([[1.1239, 2.2465, 1.5674],
        [1.1159, 2.0936, 1.7787]]) tensor([[1.1239, 2.2465, 1.5674],
        [1.1159, 2.0936, 1.7787]])


In [47]:
##Reshaping

In [49]:
x = torch.arange(9)

x_3x3 = x.view(3,3)
print(x_3x3)
x_3x3 = x.reshape(3,3)
print(x_3x3) 

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [50]:
y = x_3x3.t()

In [55]:
print(y.contiguous().view(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [56]:
x1 = torch.rand((2,5))

In [57]:
x2 = torch.rand((2,5))

In [58]:
print(torch.cat((x1,x2), dim=0).shape)

torch.Size([4, 5])


In [59]:
print(torch.cat((x1,x2), dim=1).shape)

torch.Size([2, 10])


In [62]:
print((x1.view(1,-1)).shape)

torch.Size([1, 10])
