In [5]:
pip install torch


  Using cached mkl-2021.4.0-py2.py3-none-win_amd64.whl.metadata (1.4 kB)
  Using cached intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl.metadata (1.2 kB)
  Using cached tbb-2021.12.0-py3-none-win_amd64.whl.metadata (1.1 kB)
   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/159.8 MB 1.3 MB/s eta 0:02:05
   ---------------------------------------- 0.2/159.8 MB 2.4 MB/s eta 0:01:08
   ---------------------------------------- 0.4/159.8 MB 2.8 MB/s eta 0:00:58
   ---------------------------------------- 0.6/159.8 MB 3.9 MB/s eta 0:00:42
   ---------------------------------------- 0.8/159.8 MB 4.2 MB/s eta 0:00:38
   ---------------------------------------- 1.0/159.8 MB 4.2 MB/s eta 0:00:38
   ---------------------------------------- 1.3/159.8 MB 4.5 MB/s eta 0:00:36
   ---------------------------------------- 1.5/159.8 MB 4.6 MB/s eta 0:00:35
   ---------------------------------------- 2.0/159.8 MB 5.0 MB/s eta 0:00:32
 

In [6]:
import torch

In [9]:
print(torch.__version__)

2.3.0+cpu


In [10]:
import numpy as np

In [11]:
list = [1,2,3,4,6]
arr = np.array(list)

In [12]:
arr.dtype

dtype('int32')

In [15]:
#Convert the numpy to pytorch tensors
tensors = torch.from_numpy(arr)
tensors

tensor([1, 2, 3, 4, 6], dtype=torch.int32)

In [17]:
tensors[3]

tensor(4, dtype=torch.int32)

In [18]:
#Zeros 
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [21]:
#Arithmetic Operations

a = torch.tensor([3,4,5], dtype= torch.float)
b = torch.tensor([4,5,7], dtype= torch.float)
c = torch.zeros(3,3, dtype = float)
c =a+b
print(c)

tensor([ 7.,  9., 12.])


In [22]:
torch.add(a,b)

tensor([ 7.,  9., 12.])

In [23]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [29]:
a = torch.tensor(np.arange(0,15).reshape(5,3))

In [30]:
print(a)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)


In [31]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]], dtype=torch.int32)

In [32]:
torch.add(a,b).sum()

tensor(185.)

In [33]:
#Dot Products nd Multiplication

In [34]:
x = torch.tensor([3,4,5],dtype= torch.float64)
y = torch.tensor([6,7,8],dtype= torch.float64)


In [35]:
x.mul(y)

tensor([18., 28., 40.], dtype=torch.float64)

In [36]:
x.dot(y)

tensor(86., dtype=torch.float64)

In [39]:
x = torch.tensor([[3,4,5],[1,2,3]],dtype= torch.float64)
y = torch.tensor([[6,7,8],[3,4,5],[4,5,6]],dtype= torch.float64)


In [40]:
torch.matmul(x,y)

tensor([[50., 62., 74.],
        [24., 30., 36.]], dtype=torch.float64)

In [41]:
torch.mm(x,y)

tensor([[50., 62., 74.],
        [24., 30., 36.]], dtype=torch.float64)

In [42]:
x@y

tensor([[50., 62., 74.],
        [24., 30., 36.]], dtype=torch.float64)